// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxpvnrlpsnqpakcjwilt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4cHZucmxwc25xcGFrY2p3aWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzNjIxMDAsImV4cCI6MjA1MTkzODEwMH0.haZicXzTVHSYwIbk9Z4Ne09WK81sFea0jAla6AfQpk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);